# Site settings
title: John M. Born
author: John M. Born
email: johnmborn4@gmail.com
description: >-
  Just a website where I sporadically update the internet on my life.
baseurl: ""
url: "https://greenninja4.github.io"
# post_title: Posts
# show_excerpts: True

# Social media
github_username:  Greenninja4
linkedin_username: john-m-born
instagram_username: johnm.born
twitter_username: JohnMBorn

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-assets

# Google analytics
google_analytics: UA-140822027-1

# Jekyll assets plugin?
assets:
  sources:
    - _assets/
    - _assets/js/